# Generated by Django 2.0.10 on 2019-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0002_auto_20190201_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
