# Generated by Django 2.0.10 on 2019-02-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0005_data_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dates',
            new_name='date',
        ),
    ]
