# Generated by Django 2.1.7 on 2019-05-01 03:08

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0006_auto_20190202_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 3, 8, 7, 732360, tzinfo=utc)),
        ),
    ]
