# Generated by Django 3.2.5 on 2025-02-22 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0009_auto_20190618_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full Name', max_length=200)),
                ('mobile_number', models.BigIntegerField(help_text='Mobile number of owner')),
                ('field_1', models.CharField(help_text='Flat, House no., Building, Company, Apartment :', max_length=200)),
            ],
            options={
                'ordering': ['building', 'field_1'],
            },
        ),
        migrations.RemoveField(
            model_name='building',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='appartement',
        ),
        migrations.AddField(
            model_name='building',
            name='pin_code',
            field=models.IntegerField(default=676121, validators=[django.core.validators.RegexValidator('[1-9]{1}[0-9]{2}\\\\s{0, 1}[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Appartement',
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esp8266.building'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esp8266.apartment'),
        ),
    ]
