install:
  - pip install -r requirements.txt
language: python
python:
  - "3.8"
env:
  global:
    - DJANGO_SETTINGS_MODULE="iot.settings"
    - PYTHONPATH="/home/travis/build/sajankp/iot_project"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=3.2.5
script:
  - pytest
git:
    submodules: false
