install:
  - pip install -r requirements.txt
language: python
python:
  - "3.6"
services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="iot.settings"
    - PYTHONPATH="/home/travis/build/sajankp/iot_project"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=2.1.7 DB=postgresql

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres
script:
  - pytest
git:
    submodules: false
